FORMAT: 1A
HOST: http://api.epmap.org

# 青悦科技

国控实时空气质量查询

## 国控城市及监测点API [/api/v1/air/station_list]

### List [GET]

+ Response 200 (application/json)
    
        [
        {
            success: true,
            data: [
            {
                city: "寿光市",
                city_code: "0",
                station: "监测站",
                station_code: "1959A",
                lng: 118.746,
                lat: 36.881
            },
            {
                city: "寿光市",
                city_code: "0",
                station: "世纪学校",
                station_code: "1960A",
                lng: 118.78,
                lat: 36.864
            },
            ......
        ]

## 指定城市空气质量API [/api/v1/air/city?city={city_name}]

### List [GET]
+ Parameters
    + city_name (required, string, `上海市`) ... 城市名称
+ Response 200 (application/json)

            {
                success: true,
                data: {
                    city: "上海市",
                    city_code: "370783",
                    AQI: "120.0",
                    pollutions: "臭氧1小时",
                    level: "3",
                    SO2: "26.0",
                    NO2: "15.0",
                    CO: "0.8",
                    O3: "239.0",
                    PM2_5: "46.0",
                    PM10: "100.0",
                    longitude: "118.763",
                    latitude: "36.8725",
                    pubtime: "2016-08-24 13:00:00"
                }
            }